name: inpainting
channels:
  - anaconda
  - pytorch
  - defaults
dependencies:
  - argon2-cffi=20.1.0=py38h2bbff1b_1
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=4.0.0=pyhd3eb1b0_0
  - brotli=1.0.9=ha925a31_2
  - ca-certificates=2021.10.26=haa95532_2
  - certifi=2021.10.8=py38haa95532_0
  - cffi=1.15.0=py38h2bbff1b_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - cpuonly=2.0=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.5.1=py38hd77b12b_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py38_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - glob2=0.7=py_0
  - icu=58.2=ha925a31_3
  - importlib-metadata=4.8.2=py38haa95532_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - intel-openmp=2021.4.0=haa95532_3556
  - ipykernel=6.4.1=py38haa95532_1
  - ipython=7.29.0=py38hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.0=py38haa95532_1
  - jinja2=3.0.2=pyhd3eb1b0_0
  - jpeg=9d=h2bbff1b_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter=1.0.0=py38_7
  - jupyter_client=7.0.6=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py38haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.3.1=py38hd77b12b_0
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.2.0=hd0e1b90_0
  - libuv=1.40.0=he774522_0
  - libwebp=1.2.0=h2bbff1b_0
  - lz4-c=1.9.3=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.0.1=py38h2bbff1b_0
  - matplotlib=3.5.0=py38haa95532_0
  - matplotlib-base=3.5.0=py38h6214cd6_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py38he774522_1000
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py38h2bbff1b_0
  - mkl_fft=1.3.1=py38h277e83a_0
  - mkl_random=1.2.2=py38hf11a4ad_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=py_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py38haa95532_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.6=py38haa95532_0
  - numpy-base=1.21.2=py38h0829f74_0
  - olefile=0.46=pyhd3eb1b0_0
  - openssl=1.1.1l=h2bbff1b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.4.3=py38haa95532_1
  - parso=0.8.2=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.2.2=py38haa95532_0
  - prometheus_client=0.12.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py38ha925a31_4
  - pyrsistent=0.18.0=py38h196d8e1_0
  - python=3.8.12=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=1.10.0=py3.8_cpu_0
  - pytorch-mutex=1.0=cpu
  - pywin32=228=py38hbaba5e8_1
  - pywinpty=0.5.7=py38_0
  - pyzmq=22.3.0=py38hd77b12b_2
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=5.1.1=pyhd3eb1b0_0
  - qtpy=1.10.0=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py38haa95532_0
  - sip=4.19.13=py38ha925a31_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=h2bbff1b_0
  - terminado=0.9.4=py38haa95532_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.11=h2bbff1b_0
  - torchaudio=0.10.0=py38_cpu
  - torchvision=0.11.1=py38_cpu
  - tornado=6.1=py38h2bbff1b_0
  - tqdm=4.62.3=pyhd3eb1b0_1
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - wheel=0.37.0=pyhd3eb1b0_1
  - widgetsnbextension=3.5.1=py38_0
  - wincertstore=0.2=py38haa95532_2
  - winpty=0.4.3=4
  - xz=5.2.5=h62dcd97_0
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.9=h19a0ad4_0
  - pip:
    - argparse==1.4.0
    - imageio==2.13.5
    - networkx==2.6.3
    - numpy==1.22.0
    - pillow==9.0.0
    - pywavelets==1.2.0
    - scikit-image==0.19.1
    - scipy==1.7.3
    - tifffile==2021.11.2
prefix: C:\Users\Matthias\anaconda3\envs\inpainting
